/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import app.Application;
import custom_components.SVGImage;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.TimerTask;
import javax.swing.DefaultCellEditor;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Asus
 */
public class FrmBaoCaoThongKe extends javax.swing.JFrame implements MouseListener {

    private Color mouseHoverColor = new Color(45, 45, 45);
    private Color sidebarMenuColor = new Color(40, 50, 60);
    private Color mouseClickColor = new Color(0, 0, 0);
    private Color tabPanelHoverColor = new Color(230, 230, 230);
    private Color tabPanelLeaveColor = new Color(255, 255, 255);
    private Color lineTabHoverColor = new Color(51, 153, 255);
    private Color lineTabLeaveColor = new Color(255, 255, 255);

    private Color labelColor = new Color(153, 153, 153);
    private Color labelFocusColor = Color.BLUE;
    private Object listTextbox[];
    private JLabel listLabelForTextBox[];
    private JLabel listLineForTextBox[];

    private Object tabSelected;
    
    private Object[] menubarButtons, sidebarMenuButtons, menubarIcons, sidebarMenuLabels;

    /**
     * Creates new form frmQLNV
     */
    public FrmBaoCaoThongKe() {
        initComponents();

        menubarButtons = new Object[] {btnTrangChu, btnQLNhanVien, btnQLDuKhach, btnQLTour, btnQLVe, btnQLLoTrinh, btnBaoCaoThongKe};
        sidebarMenuButtons = new Object[] {btnTrangChuChild, btnQLNhanVienChild, btnQLDuKhachChild, btnQLTourChild, btnQLVeChild, btnQLLoTrinhChild, btnBaoCaoThongKeChild};
        menubarIcons = new Object[] {iconTrangChu, iconQLNhanVien, iconQLDuKhach, iconQLTour, iconQLVe, iconQLLoTrinh, iconBaoCaoThongKe};
        sidebarMenuLabels = new Object[] {lblTrangChu, lblQLNhanVien, lblQLDuKhach, lblQLTour, lblQLVe, lblQLLoTrinh, lblBaoCaoThongKe};
        
        addControls();
        addEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        menuBarIcon = new javax.swing.JPanel();
        pnLogo = new javax.swing.JPanel();
        logo = new custom_components.SVGImage();
        btnTrangChu = new javax.swing.JPanel();
        iconTrangChu = new custom_components.SVGImage();
        btnQLNhanVien = new javax.swing.JPanel();
        iconQLNhanVien = new custom_components.SVGImage();
        btnQLDuKhach = new javax.swing.JPanel();
        iconQLDuKhach = new custom_components.SVGImage();
        btnQLTour = new javax.swing.JPanel();
        iconQLTour = new custom_components.SVGImage();
        btnQLVe = new javax.swing.JPanel();
        iconQLVe = new custom_components.SVGImage();
        btnQLLoTrinh = new javax.swing.JPanel();
        iconQLLoTrinh = new custom_components.SVGImage();
        btnBaoCaoThongKe = new javax.swing.JPanel();
        iconBaoCaoThongKe = new custom_components.SVGImage();
        sidebarMenu = new javax.swing.JPanel();
        pnTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnTrangChuChild = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        btnQLNhanVienChild = new javax.swing.JPanel();
        lblQLNhanVien = new javax.swing.JLabel();
        btnQLDuKhachChild = new javax.swing.JPanel();
        lblQLDuKhach = new javax.swing.JLabel();
        btnQLTourChild = new javax.swing.JPanel();
        lblQLTour = new javax.swing.JLabel();
        btnQLVeChild = new javax.swing.JPanel();
        lblQLVe = new javax.swing.JLabel();
        btnQLLoTrinhChild = new javax.swing.JPanel();
        lblQLLoTrinh = new javax.swing.JLabel();
        btnBaoCaoThongKeChild = new javax.swing.JPanel();
        lblBaoCaoThongKe = new javax.swing.JLabel();
        pnBody = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        btnThongTin = new custom_components.SVGImage();
        btnThongBao = new custom_components.SVGImage();
        btnCaiDat = new custom_components.SVGImage();
        btnTaiKhoan = new custom_components.SVGImage();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnChucNang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxSuggestion1 = new custom_components.ComboBoxSuggestion();
        buttonCustom1 = new custom_components.ButtonCustom();
        btnDayStart = new custom_components.ButtonCustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDayEnd = new custom_components.ButtonCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new custom_components.TableCustom();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý tour du lịch");
        setMinimumSize(new java.awt.Dimension(1100, 750));
        setName(""); // NOI18N

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.BorderLayout());

        menuBar.setBackground(new java.awt.Color(204, 0, 204));
        menuBar.setPreferredSize(new java.awt.Dimension(65, 600));
        menuBar.setLayout(new java.awt.BorderLayout());

        menuBarIcon.setBackground(new java.awt.Color(40, 50, 60));
        menuBarIcon.setPreferredSize(new java.awt.Dimension(65, 732));

        pnLogo.setBackground(new java.awt.Color(24, 120, 189));
        pnLogo.setPreferredSize(new java.awt.Dimension(65, 60));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnLogoLayout = new javax.swing.GroupLayout(pnLogo);
        pnLogo.setLayout(pnLogoLayout);
        pnLogoLayout.setHorizontalGroup(
            pnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnLogoLayout.setVerticalGroup(
            pnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnTrangChu.setBackground(new java.awt.Color(40, 50, 60));
        btnTrangChu.setPreferredSize(new java.awt.Dimension(65, 48));

        iconTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnTrangChuLayout = new javax.swing.GroupLayout(btnTrangChu);
        btnTrangChu.setLayout(btnTrangChuLayout);
        btnTrangChuLayout.setHorizontalGroup(
            btnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrangChuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnTrangChuLayout.setVerticalGroup(
            btnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrangChuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLNhanVien.setBackground(new java.awt.Color(40, 50, 60));
        btnQLNhanVien.setPreferredSize(new java.awt.Dimension(65, 48));

        iconQLNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLNhanVienLayout = new javax.swing.GroupLayout(btnQLNhanVien);
        btnQLNhanVien.setLayout(btnQLNhanVienLayout);
        btnQLNhanVienLayout.setHorizontalGroup(
            btnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLNhanVienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLNhanVienLayout.setVerticalGroup(
            btnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLNhanVienLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLDuKhach.setBackground(new java.awt.Color(40, 50, 60));
        btnQLDuKhach.setPreferredSize(new java.awt.Dimension(65, 48));

        iconQLDuKhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLDuKhachLayout = new javax.swing.GroupLayout(btnQLDuKhach);
        btnQLDuKhach.setLayout(btnQLDuKhachLayout);
        btnQLDuKhachLayout.setHorizontalGroup(
            btnQLDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLDuKhachLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLDuKhachLayout.setVerticalGroup(
            btnQLDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLDuKhachLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLTour.setBackground(new java.awt.Color(40, 50, 60));
        btnQLTour.setPreferredSize(new java.awt.Dimension(65, 48));

        iconQLTour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLTourLayout = new javax.swing.GroupLayout(btnQLTour);
        btnQLTour.setLayout(btnQLTourLayout);
        btnQLTourLayout.setHorizontalGroup(
            btnQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLTourLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLTour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLTourLayout.setVerticalGroup(
            btnQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLTourLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLTour, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLVe.setBackground(new java.awt.Color(40, 50, 60));
        btnQLVe.setPreferredSize(new java.awt.Dimension(65, 48));

        iconQLVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLVeLayout = new javax.swing.GroupLayout(btnQLVe);
        btnQLVe.setLayout(btnQLVeLayout);
        btnQLVeLayout.setHorizontalGroup(
            btnQLVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLVeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLVe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLVeLayout.setVerticalGroup(
            btnQLVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLVeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLVe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLLoTrinh.setBackground(new java.awt.Color(40, 50, 60));
        btnQLLoTrinh.setPreferredSize(new java.awt.Dimension(65, 48));

        iconQLLoTrinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLLoTrinhLayout = new javax.swing.GroupLayout(btnQLLoTrinh);
        btnQLLoTrinh.setLayout(btnQLLoTrinhLayout);
        btnQLLoTrinhLayout.setHorizontalGroup(
            btnQLLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLLoTrinhLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLLoTrinhLayout.setVerticalGroup(
            btnQLLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLLoTrinhLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnBaoCaoThongKe.setBackground(new java.awt.Color(40, 50, 60));
        btnBaoCaoThongKe.setPreferredSize(new java.awt.Dimension(65, 48));

        iconBaoCaoThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnBaoCaoThongKeLayout = new javax.swing.GroupLayout(btnBaoCaoThongKe);
        btnBaoCaoThongKe.setLayout(btnBaoCaoThongKeLayout);
        btnBaoCaoThongKeLayout.setHorizontalGroup(
            btnBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBaoCaoThongKeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconBaoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnBaoCaoThongKeLayout.setVerticalGroup(
            btnBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBaoCaoThongKeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconBaoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuBarIconLayout = new javax.swing.GroupLayout(menuBarIcon);
        menuBarIcon.setLayout(menuBarIconLayout);
        menuBarIconLayout.setHorizontalGroup(
            menuBarIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarIconLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuBarIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLDuKhach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLLoTrinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaoCaoThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menuBarIconLayout.setVerticalGroup(
            menuBarIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarIconLayout.createSequentialGroup()
                .addComponent(pnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBaoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 354, Short.MAX_VALUE))
        );

        menuBar.add(menuBarIcon, java.awt.BorderLayout.LINE_START);

        sidebarMenu.setBackground(new java.awt.Color(40, 50, 60));

        pnTitle.setBackground(new java.awt.Color(70, 150, 220));
        pnTitle.setPreferredSize(new java.awt.Dimension(175, 60));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("TOURS");

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnTrangChuChild.setBackground(new java.awt.Color(40, 50, 60));
        btnTrangChuChild.setPreferredSize(new java.awt.Dimension(175, 48));

        lblTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setText("Trang chủ");

        javax.swing.GroupLayout btnTrangChuChildLayout = new javax.swing.GroupLayout(btnTrangChuChild);
        btnTrangChuChild.setLayout(btnTrangChuChildLayout);
        btnTrangChuChildLayout.setHorizontalGroup(
            btnTrangChuChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrangChuChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnTrangChuChildLayout.setVerticalGroup(
            btnTrangChuChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTrangChuChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTrangChu)
                .addContainerGap())
        );

        btnQLNhanVienChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLNhanVienChild.setPreferredSize(new java.awt.Dimension(175, 48));

        lblQLNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNhanVien.setText("Quản lý nhân viên");

        javax.swing.GroupLayout btnQLNhanVienChildLayout = new javax.swing.GroupLayout(btnQLNhanVienChild);
        btnQLNhanVienChild.setLayout(btnQLNhanVienChildLayout);
        btnQLNhanVienChildLayout.setHorizontalGroup(
            btnQLNhanVienChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLNhanVienChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLNhanVienChildLayout.setVerticalGroup(
            btnQLNhanVienChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLNhanVienChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLNhanVien)
                .addContainerGap())
        );

        btnQLDuKhachChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLDuKhachChild.setPreferredSize(new java.awt.Dimension(175, 48));

        lblQLDuKhach.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLDuKhach.setForeground(new java.awt.Color(255, 255, 255));
        lblQLDuKhach.setText("Quản lý du khách");

        javax.swing.GroupLayout btnQLDuKhachChildLayout = new javax.swing.GroupLayout(btnQLDuKhachChild);
        btnQLDuKhachChild.setLayout(btnQLDuKhachChildLayout);
        btnQLDuKhachChildLayout.setHorizontalGroup(
            btnQLDuKhachChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLDuKhachChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLDuKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLDuKhachChildLayout.setVerticalGroup(
            btnQLDuKhachChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLDuKhachChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLDuKhach)
                .addContainerGap())
        );

        btnQLTourChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLTourChild.setPreferredSize(new java.awt.Dimension(175, 48));

        lblQLTour.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLTour.setForeground(new java.awt.Color(255, 255, 255));
        lblQLTour.setText("Quản lý tour");

        javax.swing.GroupLayout btnQLTourChildLayout = new javax.swing.GroupLayout(btnQLTourChild);
        btnQLTourChild.setLayout(btnQLTourChildLayout);
        btnQLTourChildLayout.setHorizontalGroup(
            btnQLTourChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLTourChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLTour, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLTourChildLayout.setVerticalGroup(
            btnQLTourChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLTourChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLTour)
                .addContainerGap())
        );

        btnQLVeChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLVeChild.setPreferredSize(new java.awt.Dimension(175, 48));

        lblQLVe.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQLVe.setText("Quản lý vé");

        javax.swing.GroupLayout btnQLVeChildLayout = new javax.swing.GroupLayout(btnQLVeChild);
        btnQLVeChild.setLayout(btnQLVeChildLayout);
        btnQLVeChildLayout.setHorizontalGroup(
            btnQLVeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLVeChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLVe, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLVeChildLayout.setVerticalGroup(
            btnQLVeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLVeChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLVe)
                .addContainerGap())
        );

        btnQLLoTrinhChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLLoTrinhChild.setPreferredSize(new java.awt.Dimension(175, 48));

        lblQLLoTrinh.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLLoTrinh.setForeground(new java.awt.Color(255, 255, 255));
        lblQLLoTrinh.setText("Quản lý lộ trình");

        javax.swing.GroupLayout btnQLLoTrinhChildLayout = new javax.swing.GroupLayout(btnQLLoTrinhChild);
        btnQLLoTrinhChild.setLayout(btnQLLoTrinhChildLayout);
        btnQLLoTrinhChildLayout.setHorizontalGroup(
            btnQLLoTrinhChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLLoTrinhChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLLoTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLLoTrinhChildLayout.setVerticalGroup(
            btnQLLoTrinhChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLLoTrinhChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLLoTrinh)
                .addContainerGap())
        );

        btnBaoCaoThongKeChild.setBackground(new java.awt.Color(40, 50, 60));
        btnBaoCaoThongKeChild.setPreferredSize(new java.awt.Dimension(175, 48));

        lblBaoCaoThongKe.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblBaoCaoThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblBaoCaoThongKe.setText("Báo cáo thống kê");

        javax.swing.GroupLayout btnBaoCaoThongKeChildLayout = new javax.swing.GroupLayout(btnBaoCaoThongKeChild);
        btnBaoCaoThongKeChild.setLayout(btnBaoCaoThongKeChildLayout);
        btnBaoCaoThongKeChildLayout.setHorizontalGroup(
            btnBaoCaoThongKeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBaoCaoThongKeChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblBaoCaoThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBaoCaoThongKeChildLayout.setVerticalGroup(
            btnBaoCaoThongKeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBaoCaoThongKeChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblBaoCaoThongKe)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidebarMenuLayout = new javax.swing.GroupLayout(sidebarMenu);
        sidebarMenu.setLayout(sidebarMenuLayout);
        sidebarMenuLayout.setHorizontalGroup(
            sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrangChuChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLNhanVienChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLDuKhachChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLTourChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLVeChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLLoTrinhChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaoCaoThongKeChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        sidebarMenuLayout.setVerticalGroup(
            sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarMenuLayout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTrangChuChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNhanVienChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLDuKhachChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLTourChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLVeChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLLoTrinhChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBaoCaoThongKeChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 354, Short.MAX_VALUE))
        );

        menuBar.add(sidebarMenu, java.awt.BorderLayout.CENTER);

        pnMain.add(menuBar, java.awt.BorderLayout.LINE_START);

        pnBody.setOpaque(false);
        pnBody.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1092, 60));

        lblPageTitle.setFont(new java.awt.Font("Mulish ExtraBold", 1, 27)); // NOI18N
        lblPageTitle.setText("Báo cáo thống kê");

        btnThongTin.setBackground(new java.awt.Color(204, 204, 204));
        btnThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongTin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThongTin.setOpaque(true);

        btnThongBao.setBackground(new java.awt.Color(204, 204, 204));
        btnThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongBao.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThongBao.setOpaque(true);

        btnCaiDat.setBackground(new java.awt.Color(204, 204, 204));
        btnCaiDat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCaiDat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnCaiDat.setOpaque(true);
        btnCaiDat.setPreferredSize(new java.awt.Dimension(40, 40));

        btnTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        btnTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTaiKhoan.setOpaque(true);
        btnTaiKhoan.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel2.setBackground(new java.awt.Color(240, 240, 240));
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblPageTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 605, Short.MAX_VALUE)
                        .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPageTitle))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBody.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        pnChucNang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Loại thống kê");
        jLabel1.setToolTipText("");

        comboBoxSuggestion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thống kê du khách", "Thống kê doanh thu", "Thống kê vé", "Thống kê cập nhật" }));
        comboBoxSuggestion1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        buttonCustom1.setBackground(new java.awt.Color(0, 153, 51));
        buttonCustom1.setBorder(null);
        buttonCustom1.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustom1.setText("Xuất báo cáo");
        buttonCustom1.setToolTipText("");
        buttonCustom1.setBorderColor(new java.awt.Color(0, 153, 51));
        buttonCustom1.setColor(new java.awt.Color(0, 153, 51));
        buttonCustom1.setColorClick(new java.awt.Color(0, 153, 102));
        buttonCustom1.setColorHover(new java.awt.Color(0, 153, 102));
        buttonCustom1.setFont(new java.awt.Font("Mulish Medium", 1, 13)); // NOI18N
        buttonCustom1.setRadius(10);
        buttonCustom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonCustom1MousePressed(evt);
            }
        });

        btnDayStart.setBorder(null);
        btnDayStart.setText("20 May 2022");
        btnDayStart.setBorderColor(new java.awt.Color(240, 240, 240));
        btnDayStart.setColorClick(new java.awt.Color(200, 200, 200));
        btnDayStart.setColorHover(new java.awt.Color(200, 200, 200));
        btnDayStart.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDayStart.setRadius(10);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Từ:");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Đến");
        jLabel4.setToolTipText("");

        btnDayEnd.setBorder(null);
        btnDayEnd.setText("01 Jut 2022");
        btnDayEnd.setBorderColor(new java.awt.Color(240, 240, 240));
        btnDayEnd.setColorClick(new java.awt.Color(200, 200, 200));
        btnDayEnd.setColorHover(new java.awt.Color(200, 200, 200));
        btnDayEnd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDayEnd.setRadius(10);
        btnDayEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDayEndMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDayStart, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDayStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnDayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tbNhanVien.setForeground(new java.awt.Color(0, 51, 102));
        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Mã NV", "Tên nhân viên", "Vai trò", "Số điện thoại", "Email", "Ghi chú", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbNhanVien.setGridColor(new java.awt.Color(255, 255, 255));
        tbNhanVien.setHeaderColor(new java.awt.Color(0, 204, 51));
        tbNhanVien.setHeaderFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbNhanVien.setHeaderFontColor(new java.awt.Color(255, 255, 255));
        tbNhanVien.setHeaderHeight(40);
        tbNhanVien.setHeaderTextAlign(1);
        tbNhanVien.setRowHeight(30);
        tbNhanVien.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tbNhanVien.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbNhanVien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pnBody.add(jPanel3, java.awt.BorderLayout.CENTER);

        pnMain.add(pnBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1200, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustom1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCustom1MousePressed
        //sidebarMenuHide();
    }//GEN-LAST:event_buttonCustom1MousePressed

    private void btnDayEndMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDayEndMousePressed
        //sidebarMenuShow();
    }//GEN-LAST:event_btnDayEndMousePressed

    private int sidebarMenuChildShow = 175;
    private boolean sidebarMouseHover = false;
    private int sidebarIconWidth = 23;
    private int sidebarIconHeigth = 23;
    private Color sidebarIconColor = Color.WHITE;

    private void addControls() {

        iconTrangChu.setSVGImage("svg/house-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconTrangChu.setColor(sidebarIconColor);
        iconQLNhanVien.setSVGImage("svg/clipboard-user-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLNhanVien.setColor(sidebarIconColor);
        iconQLDuKhach.setSVGImage("svg/person-skiing-nordic-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLDuKhach.setColor(sidebarIconColor);
        iconQLTour.setSVGImage("svg/torii-gate-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLTour.setColor(sidebarIconColor);
        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);
        iconQLLoTrinh.setSVGImage("svg/plane-departure-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLLoTrinh.setColor(sidebarIconColor);
        iconBaoCaoThongKe.setSVGImage("svg/chart-pie-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconBaoCaoThongKe.setColor(sidebarIconColor);

        logo.setSVGImage("svg/atom-solid.svg", 32, 32);
        logo.setColor(Color.WHITE);
        
        btnTaiKhoan.setOpaque(false);
        btnTaiKhoan.setSVGImage("svg/circle-user-solid.svg", 35, 35);
        btnTaiKhoan.setColor(Color.ORANGE);
        btnCaiDat.setOpaque(false);
        btnCaiDat.setSVGImage("svg/gear-solid.svg", 23, 23);
        btnCaiDat.setColor(Color.ORANGE);
        btnThongBao.setOpaque(false);
        btnThongBao.setSVGImage("svg/bell-solid.svg", 23, 23);
        btnThongBao.setColor(Color.orange);
        btnThongTin.setOpaque(false);
        btnThongTin.setSVGImage("svg/circle-info-solid.svg", 23, 23);
        btnThongTin.setColor(Color.orange);

//        btnThem.setSVGImage("svg/user-plus-solid.svg", 21, 17);
//        btnSua.setSVGImage("svg/user-pen-solid.svg", 21, 17);
//        btnXoa.setSVGImage("svg/trash-solid.svg", 15, 17);
        
        
        //SidebarMenuModel.createSidebarMenu(sidebarMenu, sidebarMenuChild);
        
        
    }
    
    private void addEvents() {
        menuBarIcon.addMouseListener(this);
        sidebarMenu.addMouseListener(this);
        
        btnTrangChu.addMouseListener(this);
        btnQLNhanVien.addMouseListener(this);
        btnQLDuKhach.addMouseListener(this);
        btnQLVe.addMouseListener(this);
        btnQLTour.addMouseListener(this);
        btnQLLoTrinh.addMouseListener(this);
        btnBaoCaoThongKe.addMouseListener(this);
        
        btnTrangChuChild.addMouseListener(this);
        btnQLNhanVienChild.addMouseListener(this);
        btnQLDuKhachChild.addMouseListener(this);
        btnQLVeChild.addMouseListener(this);
        btnQLTourChild.addMouseListener(this);
        btnQLLoTrinhChild.addMouseListener(this);
        btnBaoCaoThongKeChild.addMouseListener(this);
        
    }

    private void sidebarMenuShow() {
        //menuBar.setPreferredSize(new Dimension(240, menuBar.getHeight()));
//        menuBar.setSize(240, menuBar.getHeight());
//        sidebarMenu.setSize(175, sidebarMenu.getHeight());

        Thread th = new Thread() {
            @Override
            public void run() {
                try
                {
                        for(sidebarMenuChildShow = sidebarMenu.getSize().width; sidebarMenuChildShow <= 175; sidebarMenuChildShow++)
                        {
                            Thread.sleep(1);
                            menuBar.setSize(sidebarMenuChildShow + 65, menuBar.getHeight()); //System.out.println(menuBar.getWidth());
                            sidebarMenu.setSize(sidebarMenuChildShow, sidebarMenu.getSize().height);
                            if(sidebarMouseHover == false)
                                break;
                        }
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                }
            }
        };
        th.start();
    }

    private void sidebarMenuHide() {
//        System.out.println(jPanel1.getWidth());
//        menuBar.setPreferredSize(new Dimension(65, menuBar.getHeight()));
//        
//        menuBar.setSize(65, menuBar.getHeight());
//        sidebarMenu.setSize(0, sidebarMenu.getHeight());

        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (sidebarMenuChildShow = sidebarMenu.getSize().width; sidebarMenuChildShow >= 0; sidebarMenuChildShow--) {
                        Thread.sleep(1);
                        menuBar.setSize(sidebarMenuChildShow + 65, menuBar.getHeight());  //System.out.println(menuBar.getWidth());
                        sidebarMenu.setSize(sidebarMenuChildShow, sidebarMenu.getSize().height);
                        if (sidebarMouseHover == true) {
                            break;
                        }
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        };
        th.start();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBaoCaoThongKe().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBaoCaoThongKe;
    private javax.swing.JPanel btnBaoCaoThongKeChild;
    private custom_components.SVGImage btnCaiDat;
    private custom_components.ButtonCustom btnDayEnd;
    private custom_components.ButtonCustom btnDayStart;
    private javax.swing.JPanel btnQLDuKhach;
    private javax.swing.JPanel btnQLDuKhachChild;
    private javax.swing.JPanel btnQLLoTrinh;
    private javax.swing.JPanel btnQLLoTrinhChild;
    private javax.swing.JPanel btnQLNhanVien;
    private javax.swing.JPanel btnQLNhanVienChild;
    private javax.swing.JPanel btnQLTour;
    private javax.swing.JPanel btnQLTourChild;
    private javax.swing.JPanel btnQLVe;
    private javax.swing.JPanel btnQLVeChild;
    private custom_components.SVGImage btnTaiKhoan;
    private custom_components.SVGImage btnThongBao;
    private custom_components.SVGImage btnThongTin;
    private javax.swing.JPanel btnTrangChu;
    private javax.swing.JPanel btnTrangChuChild;
    private custom_components.ButtonCustom buttonCustom1;
    private custom_components.ComboBoxSuggestion comboBoxSuggestion1;
    private custom_components.SVGImage iconBaoCaoThongKe;
    private custom_components.SVGImage iconQLDuKhach;
    private custom_components.SVGImage iconQLLoTrinh;
    private custom_components.SVGImage iconQLNhanVien;
    private custom_components.SVGImage iconQLTour;
    private custom_components.SVGImage iconQLVe;
    private custom_components.SVGImage iconTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBaoCaoThongKe;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblQLDuKhach;
    private javax.swing.JLabel lblQLLoTrinh;
    private javax.swing.JLabel lblQLNhanVien;
    private javax.swing.JLabel lblQLTour;
    private javax.swing.JLabel lblQLVe;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrangChu;
    private custom_components.SVGImage logo;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel menuBarIcon;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JPanel sidebarMenu;
    private custom_components.TableCustom tbNhanVien;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        Object o = e.getSource();

        if(o.equals(pnLogo) || o.equals(btnTrangChu) || o.equals(btnTrangChuChild))
        {
            this.setVisible(false);
            Application.frmTrangChu.setVisible(true);
        }
        
        else if(o.equals(btnQLNhanVien) || o.equals(btnQLNhanVienChild))
        {
            this.setVisible(false);
            Application.frmQLNhanVien.setVisible(true);
        }
        
        else if(o.equals(btnQLDuKhach) || o.equals(btnQLDuKhachChild))
        {
            this.setVisible(false);
            Application.frmQLDuKhach.setVisible(true);
        }
        
        else if(o.equals(btnQLTour) || o.equals(btnQLTourChild))
        {
            this.setVisible(false);
            Application.frmQLTour.setVisible(true);
        }
        
        else if(o.equals(btnQLVe) || o.equals(btnQLVeChild))
        {
            this.setVisible(false);
            Application.frmQLVe.setVisible(true);
        }
        
        else if(o.equals(btnQLLoTrinh) || o.equals(btnQLLoTrinhChild))
        {
            this.setVisible(false);
            Application.frmQLLoTrinh.setVisible(true);
        }
        
        else if(o.equals(btnTaiKhoan))
        {
            Application.frmQLTTTaiKhoan.setVisible(true);
        }
        else if(o.equals(btnThongBao))
        {
            Application.frmThongBao.setVisible(true);
        }
        else if(o.equals(btnThongTin))
        {
            Application.frmThongTin.setVisible(true);
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        Object o = e.getSource();
        
        if(o.equals(btnTrangChu) || o.equals(btnQLNhanVien) || o.equals(btnQLDuKhach) || o.equals(btnQLVe) 
                || o.equals(btnQLTour) || o.equals(btnQLLoTrinh) || o.equals(btnBaoCaoThongKe)
                || o.equals(btnTrangChuChild) || o.equals(btnQLNhanVienChild) || o.equals(btnQLDuKhachChild) || o.equals(btnQLVeChild) 
                || o.equals(btnQLTourChild) || o.equals(btnQLLoTrinhChild) || o.equals(btnBaoCaoThongKeChild)
                || o.equals(lblTrangChu) || o.equals(lblQLNhanVien) || o.equals(lblQLDuKhach) || o.equals(lblQLVe)
                || o.equals(lblQLTour) || o.equals(lblQLLoTrinh) || o.equals(lblBaoCaoThongKe)) {
            JPanel jPanel = (JPanel)o;
            jPanel.setBackground(mouseHoverColor);
            sidebarMouseHover = true;
            sidebarMenuShow();
        }
        
        else if(o.equals(menuBarIcon) || o.equals(sidebarMenu))
        {
            sidebarMouseHover = true;
            sidebarMenuShow();
        }
    }

    @Override
    public void mouseExited(MouseEvent e) {
        Object o = e.getSource();
        
        if(o.equals(btnTrangChu) || o.equals(btnQLNhanVien) || o.equals(btnQLDuKhach) || o.equals(btnQLVe) 
                || o.equals(btnQLTour) || o.equals(btnQLLoTrinh) || o.equals(btnBaoCaoThongKe)
                || o.equals(btnTrangChuChild) || o.equals(btnQLNhanVienChild) || o.equals(btnQLDuKhachChild) || o.equals(btnQLVeChild) 
                || o.equals(btnQLTourChild) || o.equals(btnQLLoTrinhChild) || o.equals(btnBaoCaoThongKeChild)
                || o.equals(lblTrangChu) || o.equals(lblQLNhanVien) || o.equals(lblQLDuKhach) || o.equals(lblQLVe)
                || o.equals(lblQLTour) || o.equals(lblQLLoTrinh) || o.equals(lblBaoCaoThongKe)) {
            JPanel jPanel = (JPanel)o;
            jPanel.setBackground(sidebarMenuColor);
            sidebarMouseHover = false;
            sidebarMenuHide();
        }

        else if(o.equals(menuBarIcon) || o.equals(sidebarMenu))
        {
            sidebarMouseHover = false;
            sidebarMenuHide();
        }
    }
}
