/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.DuKhach_DAO;
import entity.DuKhach;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model_table.TableDuKhach;

/**
 *
 * @author Admin
 */
public class FrmDuKhach extends javax.swing.JFrame {
    
    private Color labelColor = new Color(153, 153, 153);
    private Color labelFocusColor = Color.BLUE;
    private Object listTextbox[];
    private JLabel listLabelForTextBox[];
    private JLabel listLineForTextBox[];
    /**
     * Creates new form FrmDuKhach
     */
    public FrmDuKhach() {
        initComponents();
        addControls();
        
    }
    
        private void addControls() {
        btnBack.setSVGImage("svg/arrow-left-solid.svg", 25, 25);
        btnBack.setColor(Color.WHITE);
        
        setlblErroEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBack = new custom_components.ButtonCustom();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnMaDuKhach = new javax.swing.JPanel();
        lblMaDuKhach = new javax.swing.JLabel();
        txtMaDuKhach = new javax.swing.JTextField();
        lineMaNhanVien = new javax.swing.JLabel();
        lblMaDuKhachError = new javax.swing.JLabel();
        pnVaiTro = new javax.swing.JPanel();
        btnXoaTrang = new javax.swing.JLabel();
        pnEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lineEmail = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        pnGhiChu = new javax.swing.JPanel();
        lblGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        lineGhiChu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnLuu = new custom_components.ButtonCustom();
        btnHuy = new custom_components.ButtonCustom();
        pnTenDuKhach = new javax.swing.JPanel();
        lblTenDuKhach = new javax.swing.JLabel();
        txtTenDuKhach = new javax.swing.JTextField();
        lineTenNhanVien = new javax.swing.JLabel();
        lblTenDuKhachError = new javax.swing.JLabel();
        pnSoDienThoai = new javax.swing.JPanel();
        lblSoDienThoai = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        lineSoDienThoai = new javax.swing.JLabel();
        lblSoDienThoaiError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        btnBack.setBorder(null);
        btnBack.setBorderColor(new java.awt.Color(255, 255, 255));
        btnBack.setRadius(45);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(559, Short.MAX_VALUE))
        );

        pnMain.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 80));

        lblPageTitle.setFont(new java.awt.Font("Mulish ExtraBold", 1, 27)); // NOI18N
        lblPageTitle.setText("Thêm du khách");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPageTitle)
                .addContainerGap(556, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblPageTitle)
                .addGap(21, 21, 21))
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setOpaque(false);

        pnMaDuKhach.setBackground(new java.awt.Color(255, 255, 255));
        pnMaDuKhach.setPreferredSize(new java.awt.Dimension(350, 83));

        lblMaDuKhach.setBackground(new java.awt.Color(255, 204, 0));
        lblMaDuKhach.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblMaDuKhach.setForeground(new java.awt.Color(102, 153, 255));
        lblMaDuKhach.setText("Mã du khách *");

        txtMaDuKhach.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaDuKhach.setForeground(new java.awt.Color(51, 51, 51));
        txtMaDuKhach.setBorder(null);
        txtMaDuKhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaDuKhachMouseClicked(evt);
            }
        });

        lineMaNhanVien.setBackground(new java.awt.Color(102, 153, 255));
        lineMaNhanVien.setOpaque(true);
        lineMaNhanVien.setPreferredSize(new java.awt.Dimension(400, 1));

        lblMaDuKhachError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMaDuKhachError.setForeground(new java.awt.Color(255, 0, 0));
        lblMaDuKhachError.setText("Mã du khách đã tồn tại trong danh sách");

        javax.swing.GroupLayout pnMaDuKhachLayout = new javax.swing.GroupLayout(pnMaDuKhach);
        pnMaDuKhach.setLayout(pnMaDuKhachLayout);
        pnMaDuKhachLayout.setHorizontalGroup(
            pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                        .addComponent(lblMaDuKhachError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                        .addComponent(lineMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                        .addGroup(pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDuKhach)
                            .addComponent(lblMaDuKhach))
                        .addGap(46, 46, 46))))
        );
        pnMaDuKhachLayout.setVerticalGroup(
            pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaDuKhach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblMaDuKhachError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnVaiTro.setBackground(new java.awt.Color(255, 255, 255));
        pnVaiTro.setPreferredSize(new java.awt.Dimension(350, 60));

        javax.swing.GroupLayout pnVaiTroLayout = new javax.swing.GroupLayout(pnVaiTro);
        pnVaiTro.setLayout(pnVaiTroLayout);
        pnVaiTroLayout.setHorizontalGroup(
            pnVaiTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        pnVaiTroLayout.setVerticalGroup(
            pnVaiTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        btnXoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaTrang.setForeground(new java.awt.Color(170, 170, 170));
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXoaTrangMousePressed(evt);
            }
        });

        pnEmail.setBackground(new java.awt.Color(255, 255, 255));
        pnEmail.setPreferredSize(new java.awt.Dimension(350, 77));

        lblEmail.setBackground(new java.awt.Color(255, 204, 0));
        lblEmail.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 153, 255));
        lblEmail.setText("Email *");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });

        lineEmail.setBackground(new java.awt.Color(102, 153, 255));
        lineEmail.setOpaque(true);
        lineEmail.setPreferredSize(new java.awt.Dimension(400, 1));

        lblEmailError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblEmailError.setText("Mã du khách đã tồn tại trong danh sách");

        javax.swing.GroupLayout pnEmailLayout = new javax.swing.GroupLayout(pnEmail);
        pnEmail.setLayout(pnEmailLayout);
        pnEmailLayout.setHorizontalGroup(
            pnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnEmailLayout.createSequentialGroup()
                        .addGroup(pnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnEmailLayout.createSequentialGroup()
                        .addComponent(lblEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnEmailLayout.setVerticalGroup(
            pnEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblEmailError)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        pnGhiChu.setPreferredSize(new java.awt.Dimension(350, 61));

        lblGhiChu.setBackground(new java.awt.Color(255, 204, 0));
        lblGhiChu.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(153, 153, 153));
        lblGhiChu.setText("Ghi chú");

        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(51, 51, 51));
        txtGhiChu.setBorder(null);
        txtGhiChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGhiChuMouseClicked(evt);
            }
        });

        lineGhiChu.setBackground(new java.awt.Color(102, 153, 255));
        lineGhiChu.setOpaque(true);
        lineGhiChu.setPreferredSize(new java.awt.Dimension(780, 1));

        javax.swing.GroupLayout pnGhiChuLayout = new javax.swing.GroupLayout(pnGhiChu);
        pnGhiChu.setLayout(pnGhiChuLayout);
        pnGhiChuLayout.setHorizontalGroup(
            pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGhiChuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnGhiChuLayout.createSequentialGroup()
                        .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnGhiChuLayout.setVerticalGroup(
            pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGhiChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGhiChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnMaDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pnMaDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnXoaTrang)
                .addGap(49, 49, 49))
        );

        jPanel6.setOpaque(false);

        btnLuu.setBackground(new java.awt.Color(72, 167, 235));
        btnLuu.setBorder(null);
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("LƯU");
        btnLuu.setBorderColor(new java.awt.Color(255, 255, 255));
        btnLuu.setColor(new java.awt.Color(72, 167, 235));
        btnLuu.setColorClick(new java.awt.Color(102, 153, 255));
        btnLuu.setColorHover(new java.awt.Color(102, 153, 255));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setRadius(35);
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLuuMousePressed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 204, 204));
        btnHuy.setBorder(null);
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY");
        btnHuy.setBorderColor(new java.awt.Color(255, 255, 255));
        btnHuy.setColor(new java.awt.Color(204, 204, 204));
        btnHuy.setColorClick(new java.awt.Color(153, 153, 153));
        btnHuy.setColorHover(new java.awt.Color(153, 153, 153));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setRadius(35);
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHuyMousePressed(evt);
            }
        });

        pnTenDuKhach.setBackground(new java.awt.Color(255, 255, 255));
        pnTenDuKhach.setPreferredSize(new java.awt.Dimension(350, 77));

        lblTenDuKhach.setBackground(new java.awt.Color(255, 204, 0));
        lblTenDuKhach.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblTenDuKhach.setForeground(new java.awt.Color(102, 153, 255));
        lblTenDuKhach.setText("Tên du khách*");

        txtTenDuKhach.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTenDuKhach.setForeground(new java.awt.Color(51, 51, 51));
        txtTenDuKhach.setBorder(null);
        txtTenDuKhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenDuKhachMouseClicked(evt);
            }
        });

        lineTenNhanVien.setBackground(new java.awt.Color(102, 153, 255));
        lineTenNhanVien.setOpaque(true);
        lineTenNhanVien.setPreferredSize(new java.awt.Dimension(400, 1));

        lblTenDuKhachError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTenDuKhachError.setForeground(new java.awt.Color(255, 0, 0));
        lblTenDuKhachError.setText("Mã du khách đã tồn tại trong danh sách");

        javax.swing.GroupLayout pnTenDuKhachLayout = new javax.swing.GroupLayout(pnTenDuKhach);
        pnTenDuKhach.setLayout(pnTenDuKhachLayout);
        pnTenDuKhachLayout.setHorizontalGroup(
            pnTenDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTenDuKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTenDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenDuKhach, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTenDuKhachLayout.createSequentialGroup()
                        .addGroup(pnTenDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenDuKhach))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnTenDuKhachLayout.createSequentialGroup()
                        .addComponent(lblTenDuKhachError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnTenDuKhachLayout.setVerticalGroup(
            pnTenDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTenDuKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenDuKhach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblTenDuKhachError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnSoDienThoai.setBackground(new java.awt.Color(255, 255, 255));
        pnSoDienThoai.setPreferredSize(new java.awt.Dimension(350, 77));

        lblSoDienThoai.setBackground(new java.awt.Color(255, 204, 0));
        lblSoDienThoai.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(102, 153, 255));
        lblSoDienThoai.setText("Số điện thoại *");

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(51, 51, 51));
        txtSoDienThoai.setBorder(null);
        txtSoDienThoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoDienThoaiMouseClicked(evt);
            }
        });

        lineSoDienThoai.setBackground(new java.awt.Color(102, 153, 255));
        lineSoDienThoai.setOpaque(true);
        lineSoDienThoai.setPreferredSize(new java.awt.Dimension(400, 1));

        lblSoDienThoaiError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSoDienThoaiError.setForeground(new java.awt.Color(255, 0, 0));
        lblSoDienThoaiError.setText("Mã du khách đã tồn tại trong danh sách");

        javax.swing.GroupLayout pnSoDienThoaiLayout = new javax.swing.GroupLayout(pnSoDienThoai);
        pnSoDienThoai.setLayout(pnSoDienThoaiLayout);
        pnSoDienThoaiLayout.setHorizontalGroup(
            pnSoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSoDienThoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnSoDienThoaiLayout.createSequentialGroup()
                        .addGroup(pnSoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoDienThoai))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnSoDienThoaiLayout.createSequentialGroup()
                        .addComponent(lblSoDienThoaiError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnSoDienThoaiLayout.setVerticalGroup(
            pnSoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSoDienThoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoDienThoai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblSoDienThoaiError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnTenDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTenDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(pnSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        pnMain.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaDuKhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaDuKhachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDuKhachMouseClicked

    private void txtTenDuKhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDuKhachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDuKhachMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMouseClicked

    private void btnXoaTrangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaTrangMousePressed
        xoaTrang();
    }//GEN-LAST:event_btnXoaTrangMousePressed

    private void txtSoDienThoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoDienThoaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiMouseClicked

    private void txtGhiChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGhiChuMouseClicked

    }//GEN-LAST:event_txtGhiChuMouseClicked

    private void btnLuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMousePressed
        luuDuKhach();
    }//GEN-LAST:event_btnLuuMousePressed

    private void btnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMousePressed
        this.dispose();
    }//GEN-LAST:event_btnHuyMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDuKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDuKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDuKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDuKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDuKhach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_components.ButtonCustom btnBack;
    private custom_components.ButtonCustom btnHuy;
    private custom_components.ButtonCustom btnLuu;
    private javax.swing.JLabel btnXoaTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblMaDuKhach;
    private javax.swing.JLabel lblMaDuKhachError;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblSoDienThoaiError;
    private javax.swing.JLabel lblTenDuKhach;
    private javax.swing.JLabel lblTenDuKhachError;
    private javax.swing.JLabel lineEmail;
    private javax.swing.JLabel lineGhiChu;
    private javax.swing.JLabel lineMaNhanVien;
    private javax.swing.JLabel lineSoDienThoai;
    private javax.swing.JLabel lineTenNhanVien;
    private javax.swing.JPanel pnEmail;
    private javax.swing.JPanel pnGhiChu;
    private javax.swing.JPanel pnMaDuKhach;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnSoDienThoai;
    private javax.swing.JPanel pnTenDuKhach;
    private javax.swing.JPanel pnVaiTro;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaDuKhach;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenDuKhach;
    // End of variables declaration//GEN-END:variables

    
    
    
    private boolean checkInput(String maDK, String tenDK, String sdt, String email) {
        setlblErroEmpty();
        
        if(maDK.isEmpty())
        {
            lblMaDuKhachError.setText("Mã du khách không được để trống");
            return false;
        }
        else if(!maDK.matches("^DK\\d{2}$"))
        {
            lblMaDuKhachError.setText("Mã du khách sai định dạng");
            return false;
        }
        
        
        else if(tenDK.isEmpty())
        {
            lblTenDuKhachError.setText("Tên du khách không được để trống");
            return false;
        }
        
        
        else if(sdt.isEmpty())
        {
            lblSoDienThoaiError.setText("Số điện thoại không được để trống");
            return false;
        }
        else if(!sdt.matches("^0\\d{9}$"))
        {
            lblSoDienThoaiError.setText("Số điện thoại sai định dạng");
            return false;
        }
        
        
        else if(email.isEmpty())
        {
            lblEmailError.setText("Email không được để trống");
            return false;
        }
        
        
        
        
        else if(TableDuKhach.dsDuKhach.indexOf(maDK) >= 0)
        {
            lblMaDuKhachError.setText("Mã du khách đã tồn tại");
            return false;
        }
        
        return true;
    }
    
    private void luuDuKhach() {
        String maDK = txtMaDuKhach.getText().trim();
        String tenDK = txtTenDuKhach.getText().trim();
       
        
        String sdt = txtSoDienThoai.getText().trim();
        String email = txtEmail.getText().trim();
        
        String txtGhiChu = this.txtGhiChu.getText().trim();
        
        if(checkInput(maDK, tenDK, sdt, email))
        {
            DuKhach duKhach = new DuKhach(maDK, tenDK, sdt, email, txtGhiChu);
            if(DuKhach_DAO.addDuKhach(duKhach))
            {
                FrmQLDuKhach.loadData();
                JOptionPane.showMessageDialog(null, "Thêm du khách thành công");
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Lưu du khách không thành công");
        }
    }
    private void xoaTrang() {
        txtMaDuKhach.setText("");
        txtTenDuKhach.setText("");
        txtEmail.setText("");
        txtSoDienThoai.setText("");
        txtGhiChu.setText(""); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    private void setlblErroEmpty() {
        lblMaDuKhachError.setText("");
        lblTenDuKhachError.setText("");
        lblSoDienThoaiError.setText("");
        lblEmailError.setText("");
        
    }
}
