/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import app.Application;
import connectDB.ConnectDB;
import custom_components.SVGImage;
import dao.NhanVien_DAO;
import entity.NhanVien;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.TimerTask;
import javax.swing.DefaultCellEditor;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.TableColumn;
import model_table.ModelTableNhanVien;
import model_table.TableNhanVien;
import static model_table.TableNhanVien.indexColDelete;
import static model_table.TableNhanVien.indexColEdit;

/**
 *
 * @author Asus
 */
public class FrmTrangChuNV extends javax.swing.JFrame implements MouseListener {

    private Color mouseHoverColor = new Color(45, 45, 45);
    private Color sidebarMenuColor = new Color(40, 50, 60);
    private Color mouseClickColor = new Color(0, 0, 0);
    private Color tabPanelHoverColor = new Color(230, 230, 230);
    private Color tabPanelLeaveColor = new Color(255, 255, 255);
    private Color lineTabHoverColor = new Color(51, 153, 255);
    private Color lineTabLeaveColor = new Color(255, 255, 255);

    private Color labelColor = new Color(153, 153, 153);
    private Color labelFocusColor = Color.BLUE;
    private Object listTextbox[];
    private JLabel listLabelForTextBox[];
    private JLabel listLineForTextBox[];

    private Object tabSelected;
    
    private Object[] menubarButtons, sidebarMenuButtons, menubarIcons, sidebarMenuLabels;
    
    private static TableNhanVien tableNhanVien;

    /**
     * Creates new form frmQLNV
     */
    public FrmTrangChuNV() {
        initComponents();

        menubarButtons = new Object[] {btnTrangChu, btnQLNhanVien, btnQLDuKhach, btnQLTour, btnQLVe, btnQLLoTrinh, btnBaoCaoThongKe};
        sidebarMenuButtons = new Object[] {btnTrangChuChild, btnQLNhanVienChild, btnQLDuKhachChild, btnQLTourChild, btnQLVeChild, btnQLLoTrinhChild, btnBaoCaoThongKeChild};
        menubarIcons = new Object[] {iconTrangChu, iconQLNhanVien, iconQLDuKhach, iconQLTour, iconQLVe, iconQLLoTrinh, iconBaoCaoThongKe};
        sidebarMenuLabels = new Object[] {lblTrangChu, lblQLNhanVien, lblQLDuKhach, lblQLTour, lblQLVe, lblQLLoTrinh, lblBaoCaoThongKe};
        
        addControls();
        addEvents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        menuBarIcon = new javax.swing.JPanel();
        pnLogo = new javax.swing.JPanel();
        logo = new custom_components.SVGImage();
        btnTrangChu = new javax.swing.JPanel();
        iconTrangChu = new custom_components.SVGImage();
        btnQLNhanVien = new javax.swing.JPanel();
        iconQLNhanVien = new custom_components.SVGImage();
        btnQLDuKhach = new javax.swing.JPanel();
        iconQLDuKhach = new custom_components.SVGImage();
        btnQLTour = new javax.swing.JPanel();
        iconQLTour = new custom_components.SVGImage();
        btnQLVe = new javax.swing.JPanel();
        iconQLVe = new custom_components.SVGImage();
        btnQLLoTrinh = new javax.swing.JPanel();
        iconQLLoTrinh = new custom_components.SVGImage();
        btnBaoCaoThongKe = new javax.swing.JPanel();
        iconBaoCaoThongKe = new custom_components.SVGImage();
        sidebarMenu = new javax.swing.JPanel();
        pnTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnTrangChuChild = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        btnQLNhanVienChild = new javax.swing.JPanel();
        lblQLNhanVien = new javax.swing.JLabel();
        btnQLDuKhachChild = new javax.swing.JPanel();
        lblQLDuKhach = new javax.swing.JLabel();
        btnQLTourChild = new javax.swing.JPanel();
        lblQLTour = new javax.swing.JLabel();
        btnQLVeChild = new javax.swing.JPanel();
        lblQLVe = new javax.swing.JLabel();
        btnQLLoTrinhChild = new javax.swing.JPanel();
        lblQLLoTrinh = new javax.swing.JLabel();
        btnBaoCaoThongKeChild = new javax.swing.JPanel();
        lblBaoCaoThongKe = new javax.swing.JLabel();
        pnBody = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        btnThongTin = new custom_components.SVGImage();
        btnThongBao = new custom_components.SVGImage();
        btnCaiDat = new custom_components.SVGImage();
        btnTaiKhoan = new custom_components.SVGImage();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnTrangChu = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelCustom1 = new custom_components.PanelCustom();
        icve = new custom_components.SVGImage();
        jLabel10 = new javax.swing.JLabel();
        panelCustom2 = new custom_components.PanelCustom();
        jLabel11 = new javax.swing.JLabel();
        icnhanvien = new custom_components.SVGImage();
        panelCustom4 = new custom_components.PanelCustom();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        icthongke = new custom_components.SVGImage();
        panelCustom6 = new custom_components.PanelCustom();
        jLabel13 = new javax.swing.JLabel();
        icdukhach = new custom_components.SVGImage();
        panelCustom10 = new custom_components.PanelCustom();
        jLabel18 = new javax.swing.JLabel();
        ictour = new custom_components.SVGImage();
        imtour = new custom_components.SVGImage();
        panelCustom7 = new custom_components.PanelCustom();
        jLabel14 = new javax.swing.JLabel();
        iclotrinh = new custom_components.SVGImage();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");
        setMinimumSize(new java.awt.Dimension(1100, 750));
        setName(""); // NOI18N

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.BorderLayout());

        menuBar.setBackground(new java.awt.Color(204, 0, 204));
        menuBar.setPreferredSize(new java.awt.Dimension(65, 600));
        menuBar.setLayout(new java.awt.BorderLayout());

        menuBarIcon.setBackground(new java.awt.Color(40, 50, 60));
        menuBarIcon.setPreferredSize(new java.awt.Dimension(65, 732));

        pnLogo.setBackground(new java.awt.Color(24, 120, 189));
        pnLogo.setPreferredSize(new java.awt.Dimension(65, 60));
        pnLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnLogoMousePressed(evt);
            }
        });

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnLogoLayout = new javax.swing.GroupLayout(pnLogo);
        pnLogo.setLayout(pnLogoLayout);
        pnLogoLayout.setHorizontalGroup(
            pnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnLogoLayout.setVerticalGroup(
            pnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnTrangChu.setBackground(new java.awt.Color(40, 50, 60));
        btnTrangChu.setPreferredSize(new java.awt.Dimension(65, 48));
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrangChuMousePressed(evt);
            }
        });

        iconTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnTrangChuLayout = new javax.swing.GroupLayout(btnTrangChu);
        btnTrangChu.setLayout(btnTrangChuLayout);
        btnTrangChuLayout.setHorizontalGroup(
            btnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrangChuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnTrangChuLayout.setVerticalGroup(
            btnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrangChuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLNhanVien.setBackground(new java.awt.Color(40, 50, 60));
        btnQLNhanVien.setPreferredSize(new java.awt.Dimension(65, 48));
        btnQLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLNhanVienMousePressed(evt);
            }
        });

        iconQLNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLNhanVienLayout = new javax.swing.GroupLayout(btnQLNhanVien);
        btnQLNhanVien.setLayout(btnQLNhanVienLayout);
        btnQLNhanVienLayout.setHorizontalGroup(
            btnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLNhanVienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLNhanVienLayout.setVerticalGroup(
            btnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLNhanVienLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLDuKhach.setBackground(new java.awt.Color(40, 50, 60));
        btnQLDuKhach.setPreferredSize(new java.awt.Dimension(65, 48));
        btnQLDuKhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLDuKhachMousePressed(evt);
            }
        });

        iconQLDuKhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLDuKhachLayout = new javax.swing.GroupLayout(btnQLDuKhach);
        btnQLDuKhach.setLayout(btnQLDuKhachLayout);
        btnQLDuKhachLayout.setHorizontalGroup(
            btnQLDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLDuKhachLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLDuKhachLayout.setVerticalGroup(
            btnQLDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLDuKhachLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLTour.setBackground(new java.awt.Color(40, 50, 60));
        btnQLTour.setPreferredSize(new java.awt.Dimension(65, 48));
        btnQLTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLTourMousePressed(evt);
            }
        });

        iconQLTour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLTourLayout = new javax.swing.GroupLayout(btnQLTour);
        btnQLTour.setLayout(btnQLTourLayout);
        btnQLTourLayout.setHorizontalGroup(
            btnQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLTourLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLTour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLTourLayout.setVerticalGroup(
            btnQLTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLTourLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLTour, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLVe.setBackground(new java.awt.Color(40, 50, 60));
        btnQLVe.setPreferredSize(new java.awt.Dimension(65, 48));
        btnQLVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLVeMousePressed(evt);
            }
        });

        iconQLVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLVeLayout = new javax.swing.GroupLayout(btnQLVe);
        btnQLVe.setLayout(btnQLVeLayout);
        btnQLVeLayout.setHorizontalGroup(
            btnQLVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLVeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLVe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLVeLayout.setVerticalGroup(
            btnQLVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLVeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLVe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnQLLoTrinh.setBackground(new java.awt.Color(40, 50, 60));
        btnQLLoTrinh.setPreferredSize(new java.awt.Dimension(65, 48));
        btnQLLoTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLLoTrinhMousePressed(evt);
            }
        });

        iconQLLoTrinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnQLLoTrinhLayout = new javax.swing.GroupLayout(btnQLLoTrinh);
        btnQLLoTrinh.setLayout(btnQLLoTrinhLayout);
        btnQLLoTrinhLayout.setHorizontalGroup(
            btnQLLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLLoTrinhLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconQLLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnQLLoTrinhLayout.setVerticalGroup(
            btnQLLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLLoTrinhLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconQLLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnBaoCaoThongKe.setBackground(new java.awt.Color(40, 50, 60));
        btnBaoCaoThongKe.setPreferredSize(new java.awt.Dimension(65, 48));
        btnBaoCaoThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBaoCaoThongKeMousePressed(evt);
            }
        });

        iconBaoCaoThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnBaoCaoThongKeLayout = new javax.swing.GroupLayout(btnBaoCaoThongKe);
        btnBaoCaoThongKe.setLayout(btnBaoCaoThongKeLayout);
        btnBaoCaoThongKeLayout.setHorizontalGroup(
            btnBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBaoCaoThongKeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconBaoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnBaoCaoThongKeLayout.setVerticalGroup(
            btnBaoCaoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBaoCaoThongKeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconBaoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuBarIconLayout = new javax.swing.GroupLayout(menuBarIcon);
        menuBarIcon.setLayout(menuBarIconLayout);
        menuBarIconLayout.setHorizontalGroup(
            menuBarIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarIconLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuBarIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLDuKhach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLLoTrinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaoCaoThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menuBarIconLayout.setVerticalGroup(
            menuBarIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarIconLayout.createSequentialGroup()
                .addComponent(pnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBaoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 347, Short.MAX_VALUE))
        );

        menuBar.add(menuBarIcon, java.awt.BorderLayout.LINE_START);

        sidebarMenu.setBackground(new java.awt.Color(40, 50, 60));

        pnTitle.setBackground(new java.awt.Color(70, 150, 220));
        pnTitle.setPreferredSize(new java.awt.Dimension(175, 60));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("TOURS");

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnTrangChuChild.setBackground(new java.awt.Color(40, 50, 60));
        btnTrangChuChild.setPreferredSize(new java.awt.Dimension(175, 48));
        btnTrangChuChild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrangChuChildMousePressed(evt);
            }
        });

        lblTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setText("Trang chủ");

        javax.swing.GroupLayout btnTrangChuChildLayout = new javax.swing.GroupLayout(btnTrangChuChild);
        btnTrangChuChild.setLayout(btnTrangChuChildLayout);
        btnTrangChuChildLayout.setHorizontalGroup(
            btnTrangChuChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrangChuChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnTrangChuChildLayout.setVerticalGroup(
            btnTrangChuChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTrangChuChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTrangChu)
                .addContainerGap())
        );

        btnQLNhanVienChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLNhanVienChild.setPreferredSize(new java.awt.Dimension(175, 48));
        btnQLNhanVienChild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLNhanVienChildMousePressed(evt);
            }
        });

        lblQLNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNhanVien.setText("Quản lý nhân viên");

        javax.swing.GroupLayout btnQLNhanVienChildLayout = new javax.swing.GroupLayout(btnQLNhanVienChild);
        btnQLNhanVienChild.setLayout(btnQLNhanVienChildLayout);
        btnQLNhanVienChildLayout.setHorizontalGroup(
            btnQLNhanVienChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLNhanVienChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLNhanVienChildLayout.setVerticalGroup(
            btnQLNhanVienChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLNhanVienChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLNhanVien)
                .addContainerGap())
        );

        btnQLDuKhachChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLDuKhachChild.setPreferredSize(new java.awt.Dimension(175, 48));
        btnQLDuKhachChild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLDuKhachChildMousePressed(evt);
            }
        });

        lblQLDuKhach.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLDuKhach.setForeground(new java.awt.Color(255, 255, 255));
        lblQLDuKhach.setText("Quản lý du khách");

        javax.swing.GroupLayout btnQLDuKhachChildLayout = new javax.swing.GroupLayout(btnQLDuKhachChild);
        btnQLDuKhachChild.setLayout(btnQLDuKhachChildLayout);
        btnQLDuKhachChildLayout.setHorizontalGroup(
            btnQLDuKhachChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLDuKhachChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLDuKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLDuKhachChildLayout.setVerticalGroup(
            btnQLDuKhachChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLDuKhachChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLDuKhach)
                .addContainerGap())
        );

        btnQLTourChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLTourChild.setPreferredSize(new java.awt.Dimension(175, 48));
        btnQLTourChild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLTourChildMousePressed(evt);
            }
        });

        lblQLTour.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLTour.setForeground(new java.awt.Color(255, 255, 255));
        lblQLTour.setText("Quản lý tour");

        javax.swing.GroupLayout btnQLTourChildLayout = new javax.swing.GroupLayout(btnQLTourChild);
        btnQLTourChild.setLayout(btnQLTourChildLayout);
        btnQLTourChildLayout.setHorizontalGroup(
            btnQLTourChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLTourChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLTour, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLTourChildLayout.setVerticalGroup(
            btnQLTourChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLTourChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLTour)
                .addContainerGap())
        );

        btnQLVeChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLVeChild.setPreferredSize(new java.awt.Dimension(175, 48));
        btnQLVeChild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLVeChildMousePressed(evt);
            }
        });

        lblQLVe.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQLVe.setText("Quản lý vé");

        javax.swing.GroupLayout btnQLVeChildLayout = new javax.swing.GroupLayout(btnQLVeChild);
        btnQLVeChild.setLayout(btnQLVeChildLayout);
        btnQLVeChildLayout.setHorizontalGroup(
            btnQLVeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLVeChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLVe, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLVeChildLayout.setVerticalGroup(
            btnQLVeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLVeChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLVe)
                .addContainerGap())
        );

        btnQLLoTrinhChild.setBackground(new java.awt.Color(40, 50, 60));
        btnQLLoTrinhChild.setPreferredSize(new java.awt.Dimension(175, 48));
        btnQLLoTrinhChild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLLoTrinhChildMousePressed(evt);
            }
        });

        lblQLLoTrinh.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblQLLoTrinh.setForeground(new java.awt.Color(255, 255, 255));
        lblQLLoTrinh.setText("Quản lý lộ trình");

        javax.swing.GroupLayout btnQLLoTrinhChildLayout = new javax.swing.GroupLayout(btnQLLoTrinhChild);
        btnQLLoTrinhChild.setLayout(btnQLLoTrinhChildLayout);
        btnQLLoTrinhChildLayout.setHorizontalGroup(
            btnQLLoTrinhChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQLLoTrinhChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblQLLoTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnQLLoTrinhChildLayout.setVerticalGroup(
            btnQLLoTrinhChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQLLoTrinhChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblQLLoTrinh)
                .addContainerGap())
        );

        btnBaoCaoThongKeChild.setBackground(new java.awt.Color(40, 50, 60));
        btnBaoCaoThongKeChild.setPreferredSize(new java.awt.Dimension(175, 48));
        btnBaoCaoThongKeChild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBaoCaoThongKeChildMousePressed(evt);
            }
        });

        lblBaoCaoThongKe.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblBaoCaoThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblBaoCaoThongKe.setText("Báo cáo thống kê");

        javax.swing.GroupLayout btnBaoCaoThongKeChildLayout = new javax.swing.GroupLayout(btnBaoCaoThongKeChild);
        btnBaoCaoThongKeChild.setLayout(btnBaoCaoThongKeChildLayout);
        btnBaoCaoThongKeChildLayout.setHorizontalGroup(
            btnBaoCaoThongKeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBaoCaoThongKeChildLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblBaoCaoThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBaoCaoThongKeChildLayout.setVerticalGroup(
            btnBaoCaoThongKeChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBaoCaoThongKeChildLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblBaoCaoThongKe)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidebarMenuLayout = new javax.swing.GroupLayout(sidebarMenu);
        sidebarMenu.setLayout(sidebarMenuLayout);
        sidebarMenuLayout.setHorizontalGroup(
            sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrangChuChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLNhanVienChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLDuKhachChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLTourChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLVeChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLLoTrinhChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaoCaoThongKeChild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        sidebarMenuLayout.setVerticalGroup(
            sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarMenuLayout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTrangChuChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNhanVienChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLDuKhachChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLTourChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLVeChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLLoTrinhChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBaoCaoThongKeChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 347, Short.MAX_VALUE))
        );

        menuBar.add(sidebarMenu, java.awt.BorderLayout.CENTER);

        pnMain.add(menuBar, java.awt.BorderLayout.LINE_START);

        pnBody.setOpaque(false);
        pnBody.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1092, 60));

        lblPageTitle.setFont(new java.awt.Font("Mulish ExtraBold", 1, 27)); // NOI18N
        lblPageTitle.setText("Home");

        btnThongTin.setBackground(new java.awt.Color(204, 204, 204));
        btnThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongTin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThongTin.setOpaque(true);

        btnThongBao.setBackground(new java.awt.Color(204, 204, 204));
        btnThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongBao.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThongBao.setOpaque(true);

        btnCaiDat.setBackground(new java.awt.Color(204, 204, 204));
        btnCaiDat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCaiDat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnCaiDat.setOpaque(true);
        btnCaiDat.setPreferredSize(new java.awt.Dimension(40, 40));

        btnTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        btnTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTaiKhoan.setOpaque(true);
        btnTaiKhoan.setPreferredSize(new java.awt.Dimension(40, 40));
        btnTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTaiKhoanMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(240, 240, 240));
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblPageTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 748, Short.MAX_VALUE)
                        .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPageTitle))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBody.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.CardLayout());

        pnTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        pnTrangChu.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setBorderColor(new java.awt.Color(204, 204, 204));
        panelCustom1.setColorClick(new java.awt.Color(204, 204, 204));
        panelCustom1.setColorHover(new java.awt.Color(204, 204, 204));
        panelCustom1.setRadius(35);
        panelCustom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustom1MousePressed(evt);
            }
        });

        icve.setMaximumSize(new java.awt.Dimension(100, 100));
        icve.setMinimumSize(new java.awt.Dimension(100, 100));
        icve.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel10.setBackground(new java.awt.Color(255, 153, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Vé");

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel10)
                .addGap(61, 61, 61)
                .addComponent(icve, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(icve, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustom1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);

        panelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom2.setBorderColor(new java.awt.Color(204, 204, 204));
        panelCustom2.setColorHover(new java.awt.Color(204, 204, 204));
        panelCustom2.setRadius(35);
        panelCustom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustom2MousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 153, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setText("Nhân Viên");

        icnhanvien.setMaximumSize(new java.awt.Dimension(100, 100));
        icnhanvien.setMinimumSize(new java.awt.Dimension(100, 100));
        icnhanvien.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom2Layout.createSequentialGroup()
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(icnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustom2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(icnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);

        panelCustom4.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom4.setBorderColor(new java.awt.Color(204, 204, 204));
        panelCustom4.setColorHover(new java.awt.Color(204, 204, 204));
        panelCustom4.setRadius(50);
        panelCustom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustom4MousePressed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 153, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));

        jLabel19.setBackground(new java.awt.Color(255, 153, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 204));
        jLabel19.setText("Thống Kê");

        icthongke.setMaximumSize(new java.awt.Dimension(100, 100));
        icthongke.setMinimumSize(new java.awt.Dimension(100, 100));
        icthongke.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panelCustom4Layout = new javax.swing.GroupLayout(panelCustom4);
        panelCustom4.setLayout(panelCustom4Layout);
        panelCustom4Layout.setHorizontalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel16)
                .addGap(46, 46, 46)
                .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(icthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelCustom4Layout.setVerticalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom4Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(icthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);

        panelCustom6.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom6.setBorderColor(new java.awt.Color(204, 204, 204));
        panelCustom6.setColorHover(new java.awt.Color(204, 204, 204));
        panelCustom6.setRadius(35);
        panelCustom6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustom6MousePressed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 153, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 139, 139));
        jLabel13.setText("Du Khách");

        icdukhach.setMaximumSize(new java.awt.Dimension(100, 100));
        icdukhach.setMinimumSize(new java.awt.Dimension(100, 100));
        icdukhach.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panelCustom6Layout = new javax.swing.GroupLayout(panelCustom6);
        panelCustom6.setLayout(panelCustom6Layout);
        panelCustom6Layout.setHorizontalGroup(
            panelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icdukhach, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panelCustom6Layout.setVerticalGroup(
            panelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icdukhach, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);

        panelCustom10.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom10.setBorderColor(new java.awt.Color(204, 204, 204));
        panelCustom10.setColorHover(new java.awt.Color(204, 204, 204));
        panelCustom10.setRadius(35);
        panelCustom10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustom10MousePressed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 153, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 51));
        jLabel18.setText("Tour");

        ictour.setMaximumSize(new java.awt.Dimension(100, 100));
        ictour.setMinimumSize(new java.awt.Dimension(100, 100));
        ictour.setPreferredSize(new java.awt.Dimension(100, 100));

        imtour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tour2.png"))); // NOI18N
        imtour.setText("sVGImage1");

        javax.swing.GroupLayout panelCustom10Layout = new javax.swing.GroupLayout(panelCustom10);
        panelCustom10.setLayout(panelCustom10Layout);
        panelCustom10Layout.setHorizontalGroup(
            panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom10Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ictour, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(imtour, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        panelCustom10Layout.setVerticalGroup(
            panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom10Layout.createSequentialGroup()
                .addGroup(panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustom10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imtour, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustom10Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(ictour, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );

        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);

        panelCustom7.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom7.setBorderColor(new java.awt.Color(204, 204, 204));
        panelCustom7.setColorHover(new java.awt.Color(204, 204, 204));
        panelCustom7.setRadius(35);
        panelCustom7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustom7MousePressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 153, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 0));
        jLabel14.setText("Lộ Trình");

        iclotrinh.setMaximumSize(new java.awt.Dimension(100, 100));
        iclotrinh.setMinimumSize(new java.awt.Dimension(100, 100));
        iclotrinh.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panelCustom7Layout = new javax.swing.GroupLayout(panelCustom7);
        panelCustom7.setLayout(panelCustom7Layout);
        panelCustom7Layout.setHorizontalGroup(
            panelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom7Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom7Layout.createSequentialGroup()
                        .addComponent(iclotrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30))))
        );
        panelCustom7Layout.setVerticalGroup(
            panelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iclotrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(panelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(panelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCustom6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCustom7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pnTrangChu.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.add(pnTrangChu, "card2");

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        pnBody.add(jPanel3, java.awt.BorderLayout.CENTER);

        pnMain.add(pnBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1200, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaoCaoThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaoCaoThongKeMousePressed
        Application.frmBCTK.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBaoCaoThongKeMousePressed

    private void btnBaoCaoThongKeChildMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaoCaoThongKeChildMousePressed
        Application.frmBCTK.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBaoCaoThongKeChildMousePressed

    private void btnTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaiKhoanMousePressed
        int n = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đăng xuất?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
        {
            Application.frmDangNhapNV.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnTaiKhoanMousePressed

    private void panelCustom1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom1MousePressed
        // TODO add your handling code here:
        FrmQLVe frmQLVe = new FrmQLVe();
        frmQLVe.setVisible(true);
    }//GEN-LAST:event_panelCustom1MousePressed

    private void panelCustom10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom10MousePressed
        // TODO add your handling code here:
        FrmQLTour frmQLTour = new FrmQLTour();
        frmQLTour.setVisible(true);
    }//GEN-LAST:event_panelCustom10MousePressed

    private void panelCustom4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom4MousePressed
        // TODO add your handling code here:
        FrmBaoCaoThongKe frmBaoCaoThongKe = new FrmBaoCaoThongKe();
        frmBaoCaoThongKe.setVisible(true);
    }//GEN-LAST:event_panelCustom4MousePressed

    private void panelCustom2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom2MousePressed
        // TODO add your handling code here:
        FrmQLNhanVien frmQLNhanVien= new FrmQLNhanVien();
        frmQLNhanVien.setVisible(true);        
    }//GEN-LAST:event_panelCustom2MousePressed

    private void panelCustom6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom6MousePressed
        // TODO add your handling code here:
        FrmQLDuKhach frmQLDuKhach= new FrmQLDuKhach();
        frmQLDuKhach.setVisible(true);
    }//GEN-LAST:event_panelCustom6MousePressed

    private void panelCustom7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCustom7MousePressed

    private void pnLogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLogoMousePressed
        
    }//GEN-LAST:event_pnLogoMousePressed

    private void btnTrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMousePressed
        
    }//GEN-LAST:event_btnTrangChuMousePressed

    private void btnQLNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNhanVienMousePressed
        Application.frmQLNhanVien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLNhanVienMousePressed

    private void btnQLDuKhachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDuKhachMousePressed
        Application.frmQLDuKhach.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDuKhachMousePressed

    private void btnQLTourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTourMousePressed
        Application.frmQLTour.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLTourMousePressed

    private void btnQLVeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLVeMousePressed
        Application.frmQLVe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLVeMousePressed

    private void btnQLLoTrinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLLoTrinhMousePressed
        Application.frmQLLoTrinh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLLoTrinhMousePressed

    private void btnTrangChuChildMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuChildMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrangChuChildMousePressed

    private void btnQLNhanVienChildMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNhanVienChildMousePressed
         Application.frmQLNhanVien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLNhanVienChildMousePressed

    private void btnQLDuKhachChildMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDuKhachChildMousePressed
         Application.frmQLDuKhach.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDuKhachChildMousePressed

    private void btnQLTourChildMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTourChildMousePressed
        Application.frmQLTour.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLTourChildMousePressed

    private void btnQLVeChildMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLVeChildMousePressed
        Application.frmQLVe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLVeChildMousePressed

    private void btnQLLoTrinhChildMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLLoTrinhChildMousePressed
        Application.frmQLLoTrinh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLLoTrinhChildMousePressed

    private int sidebarMenuChildShow = 175;
    private boolean sidebarMouseHover = false;
    private int sidebarIconWidth = 23;
    private int sidebarIconHeigth = 23;
    private Color sidebarIconColor = Color.WHITE;

    private void addControls() {

        iconTrangChu.setSVGImage("svg/house-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconTrangChu.setColor(sidebarIconColor);
        iconQLNhanVien.setSVGImage("svg/clipboard-user-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLNhanVien.setColor(sidebarIconColor);
        iconQLDuKhach.setSVGImage("svg/person-skiing-nordic-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLDuKhach.setColor(sidebarIconColor);
        iconQLTour.setSVGImage("svg/torii-gate-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLTour.setColor(sidebarIconColor);
        iconQLVe.setSVGImage("svg/ticket-simple-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLVe.setColor(sidebarIconColor);
        iconQLLoTrinh.setSVGImage("svg/plane-departure-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconQLLoTrinh.setColor(sidebarIconColor);
        iconBaoCaoThongKe.setSVGImage("svg/chart-pie-solid.svg", sidebarIconWidth, sidebarIconHeigth);
        iconBaoCaoThongKe.setColor(sidebarIconColor);

        logo.setSVGImage("svg/atom-solid.svg", 32, 32);
        logo.setColor(Color.WHITE);
        
        int w = 70;
        int h = 70;
        
        icve.setSVGImage("svg/ticket-simple-solid.svg", 130, 130);
        icve.setColor(new Color(255,153,0));
        
        ictour.setSVGImage("svg/torii-gate-solid.svg", 120, 120);
        ictour.setColor(new Color(0,102,51));
        
        iclotrinh.setSVGImage("svg/bell-solid.svg", w, h);
        iclotrinh.setColor(new Color(204,204,0));
        
        icthongke.setSVGImage("svg/chart-pie-solid.svg", 100, 100);
        icthongke.setColor(new Color(0,204,204));
        
        icnhanvien.setSVGImage("svg/user-solid.svg", w, h);
        icnhanvien.setColor(new Color(51,153,0));
        
        icdukhach.setSVGImage("svg/person-skiing-nordic-solid.svg", w, h);
        icdukhach.setColor(new Color(0,139,139));
        
       
        
        btnTaiKhoan.setOpaque(false);
        btnTaiKhoan.setSVGImage("svg/circle-user-solid.svg", 35, 35);
        btnTaiKhoan.setColor(Color.ORANGE);
        btnCaiDat.setOpaque(false);
        btnCaiDat.setSVGImage("svg/gear-solid.svg", 23, 23);
        btnCaiDat.setColor(Color.ORANGE);
        btnThongBao.setOpaque(false);
        btnThongBao.setSVGImage("svg/bell-solid.svg", 23, 23);
        btnThongBao.setColor(Color.orange);
        btnThongTin.setOpaque(false);
        btnThongTin.setSVGImage("svg/circle-info-solid.svg", 23, 23);
        btnThongTin.setColor(Color.orange);

        
        
        
    }
    
    private void addEvents() {
        menuBarIcon.addMouseListener(this);
        sidebarMenu.addMouseListener(this);
        
        btnTrangChu.addMouseListener(this);
        btnQLNhanVien.addMouseListener(this);
        btnQLDuKhach.addMouseListener(this);
        btnQLVe.addMouseListener(this);
        btnQLTour.addMouseListener(this);
        btnQLLoTrinh.addMouseListener(this);
        btnBaoCaoThongKe.addMouseListener(this);
        
        btnTrangChuChild.addMouseListener(this);
        btnQLNhanVienChild.addMouseListener(this);
        btnQLDuKhachChild.addMouseListener(this);
        btnQLVeChild.addMouseListener(this);
        btnQLTourChild.addMouseListener(this);
        btnQLLoTrinhChild.addMouseListener(this);
        btnBaoCaoThongKeChild.addMouseListener(this);
        
       
        
    }   
    
    

    private void sidebarMenuShow() {
        //menuBar.setPreferredSize(new Dimension(240, menuBar.getHeight()));
//        menuBar.setSize(240, menuBar.getHeight());
//        sidebarMenu.setSize(175, sidebarMenu.getHeight());

        Thread th = new Thread() {
            @Override
            public void run() {
                try
                {
                        for(sidebarMenuChildShow = sidebarMenu.getSize().width; sidebarMenuChildShow <= 175; sidebarMenuChildShow++)
                        {
                            Thread.sleep(1);
                            menuBar.setSize(sidebarMenuChildShow + 65, menuBar.getHeight()); //System.out.println(menuBar.getWidth());
                            sidebarMenu.setSize(sidebarMenuChildShow, sidebarMenu.getSize().height);
                            if(sidebarMouseHover == false)
                                break;
                        }
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                }
            }
        };
        th.start();
    }

    private void sidebarMenuHide() {
//        System.out.println(jPanel1.getWidth());
//        menuBar.setPreferredSize(new Dimension(65, menuBar.getHeight()));
//        
//        menuBar.setSize(65, menuBar.getHeight());
//        sidebarMenu.setSize(0, sidebarMenu.getHeight());

        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (sidebarMenuChildShow = sidebarMenu.getSize().width; sidebarMenuChildShow >= 0; sidebarMenuChildShow--) {
                        Thread.sleep(1);
                        menuBar.setSize(sidebarMenuChildShow + 65, menuBar.getHeight());  //System.out.println(menuBar.getWidth());
                        sidebarMenu.setSize(sidebarMenuChildShow, sidebarMenu.getSize().height);
                        if (sidebarMouseHover == true) {
                            break;
                        }
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        };
        th.start();
    }

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrangChuNV().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBaoCaoThongKe;
    private javax.swing.JPanel btnBaoCaoThongKeChild;
    private custom_components.SVGImage btnCaiDat;
    private javax.swing.JPanel btnQLDuKhach;
    private javax.swing.JPanel btnQLDuKhachChild;
    private javax.swing.JPanel btnQLLoTrinh;
    private javax.swing.JPanel btnQLLoTrinhChild;
    private javax.swing.JPanel btnQLNhanVien;
    private javax.swing.JPanel btnQLNhanVienChild;
    private javax.swing.JPanel btnQLTour;
    private javax.swing.JPanel btnQLTourChild;
    private javax.swing.JPanel btnQLVe;
    private javax.swing.JPanel btnQLVeChild;
    private custom_components.SVGImage btnTaiKhoan;
    private custom_components.SVGImage btnThongBao;
    private custom_components.SVGImage btnThongTin;
    private javax.swing.JPanel btnTrangChu;
    private javax.swing.JPanel btnTrangChuChild;
    private custom_components.SVGImage icdukhach;
    private custom_components.SVGImage iclotrinh;
    private custom_components.SVGImage icnhanvien;
    private custom_components.SVGImage iconBaoCaoThongKe;
    private custom_components.SVGImage iconQLDuKhach;
    private custom_components.SVGImage iconQLLoTrinh;
    private custom_components.SVGImage iconQLNhanVien;
    private custom_components.SVGImage iconQLTour;
    private custom_components.SVGImage iconQLVe;
    private custom_components.SVGImage iconTrangChu;
    private custom_components.SVGImage icthongke;
    private custom_components.SVGImage ictour;
    private custom_components.SVGImage icve;
    private custom_components.SVGImage imtour;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblBaoCaoThongKe;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblQLDuKhach;
    private javax.swing.JLabel lblQLLoTrinh;
    private javax.swing.JLabel lblQLNhanVien;
    private javax.swing.JLabel lblQLTour;
    private javax.swing.JLabel lblQLVe;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrangChu;
    private custom_components.SVGImage logo;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel menuBarIcon;
    private custom_components.PanelCustom panelCustom1;
    private custom_components.PanelCustom panelCustom10;
    private custom_components.PanelCustom panelCustom2;
    private custom_components.PanelCustom panelCustom4;
    private custom_components.PanelCustom panelCustom6;
    private custom_components.PanelCustom panelCustom7;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JPanel pnTrangChu;
    private javax.swing.JPanel sidebarMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        Object o = e.getSource();
        
        if(o.equals(btnTrangChu) || o.equals(btnQLNhanVien) || o.equals(btnQLDuKhach) || o.equals(btnQLVe) 
                || o.equals(btnQLTour) || o.equals(btnQLLoTrinh) || o.equals(btnBaoCaoThongKe)
                || o.equals(btnTrangChuChild) || o.equals(btnQLNhanVienChild) || o.equals(btnQLDuKhachChild) || o.equals(btnQLVeChild) 
                || o.equals(btnQLTourChild) || o.equals(btnQLLoTrinhChild) || o.equals(btnBaoCaoThongKeChild)
                || o.equals(lblTrangChu) || o.equals(lblQLNhanVien) || o.equals(lblQLDuKhach) || o.equals(lblQLVe)
                || o.equals(lblQLTour) || o.equals(lblQLLoTrinh) || o.equals(lblBaoCaoThongKe)) {
            JPanel jPanel = (JPanel)o;
            jPanel.setBackground(mouseHoverColor);
            sidebarMouseHover = true;
            sidebarMenuShow();
        }
        
        else if(o.equals(menuBarIcon) || o.equals(sidebarMenu))
        {
            sidebarMouseHover = true;
            sidebarMenuShow();
        }
    }

    @Override
    public void mouseExited(MouseEvent e) {
        Object o = e.getSource();
        
        if(o.equals(btnTrangChu) || o.equals(btnQLNhanVien) || o.equals(btnQLDuKhach) || o.equals(btnQLVe) 
                || o.equals(btnQLTour) || o.equals(btnQLLoTrinh) || o.equals(btnBaoCaoThongKe)
                || o.equals(btnTrangChuChild) || o.equals(btnQLNhanVienChild) || o.equals(btnQLDuKhachChild) || o.equals(btnQLVeChild) 
                || o.equals(btnQLTourChild) || o.equals(btnQLLoTrinhChild) || o.equals(btnBaoCaoThongKeChild)
                || o.equals(lblTrangChu) || o.equals(lblQLNhanVien) || o.equals(lblQLDuKhach) || o.equals(lblQLVe)
                || o.equals(lblQLTour) || o.equals(lblQLLoTrinh) || o.equals(lblBaoCaoThongKe)) {
            JPanel jPanel = (JPanel)o;
            jPanel.setBackground(sidebarMenuColor);
            sidebarMouseHover = false;
            sidebarMenuHide();
        }

        else if(o.equals(menuBarIcon) || o.equals(sidebarMenu))
        {
            sidebarMouseHover = false;
            sidebarMenuHide();
        }
    }
}
