/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import dao.VeDAO;
import entity.Ve;
import java.awt.Font;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model_table.TableVe;
import model_table.ModelTableVe;

/**
 *
 * @author LE PHUC HAU
 */
public class FrmVe extends javax.swing.JFrame {

    private Color labelColor = new Color(153, 153, 153);
    private Color labelFocusColor = Color.BLUE;
    private Object listTextbox[];
    private JLabel listLabelForTextBox[];
    private JLabel listLineForTextBox[]; 
    /**
     * Creates new form FrmVe
     */
    public FrmVe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void addControls() {
        btnBack.setSVGImage("svg/arrow-left-solid.svg", 25, 25);
        btnBack.setColor(Color.WHITE);
        
        setlblErroEmpty();
    }
    private void setlblErroEmpty() {
        lblMaVeError.setText("");
        lblMaDuKhachError.setText("");
        lblMaLoTrinhError.setText("");
        lblTenTourError.setText("");
        lblGiaVeError.setText("");
    }
    private boolean checkInput(String maVe, String maDK, String tenTour, String maLT, String giaVe, String ghiChu) {
        setlblErroEmpty();
        
        if(maVe.isEmpty())
        {
            lblMaVeError.setText("Mã vé không được để trống");
            return false;
        }
        else if(!maVe.matches("^\\d{3}$"))
        {
            lblMaVeError.setText("Mã vé sai định dạng");
            return false;
        }
        else if(maDK.isEmpty())
        {
            lblMaDuKhachError.setText("Mã du khách không được để trống");
            return false;
        }
        else if(!maDK.matches("^(DK)\\d{2}$"))
        {
            lblMaDuKhachError.setText("Mã du khách sai định dạng");
            return false;
        }
        else if(tenTour.isEmpty())
        {
            lblTenTourError.setText("Tên tour không được để trống");
            return false;
        }
        else if(maLT.isEmpty())
        {
            lblMaLoTrinhError.setText("Mã lô trình không được để trống");
            return false;
        }
        else if(!maLT.matches("^(LT)\\d{2}$"))
        {
            lblMaLoTrinhError.setText("Mã lô trình sai định dạng");
            return false;
        }   
        else if(giaVe.isEmpty())
        {
            lblGiaVeError.setText("Tên tour không được để trống");
            return false;
        }
        else if(TableVe.dsVe.indexOf(maVe) >= 0)
        {
            lblMaVe.setText("Mã vé đã tồn tại");
            return false;
        }
        
        return true;
    }
    private void xoaTrang() {
        txtMaVe.setText("");
        txtMaDuKhach.setText("");
        txtTenTour.setText("");
        txtMaLoTrinh.setText("");
        txtGiaVe.setText("");
        txtGhiChu.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBack = new custom_components.ButtonCustom();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnMaVe = new javax.swing.JPanel();
        lblMaVe = new javax.swing.JLabel();
        txtMaVe = new javax.swing.JTextField();
        lineMaVe = new javax.swing.JLabel();
        lblMaVeError = new javax.swing.JLabel();
        btnXoaTrang = new javax.swing.JLabel();
        pnTenTour = new javax.swing.JPanel();
        lblTenTour = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();
        lblTenTourError = new javax.swing.JLabel();
        lineTenTour = new javax.swing.JLabel();
        pnMaDuKhach = new javax.swing.JPanel();
        lblMaDuKhach = new javax.swing.JLabel();
        txtMaDuKhach = new javax.swing.JTextField();
        lineMaDuKhach = new javax.swing.JLabel();
        lblMaDuKhachError = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pnGiaVe = new javax.swing.JPanel();
        lblGiaVe = new javax.swing.JLabel();
        txtGiaVe = new javax.swing.JTextField();
        lblGiaVeError = new javax.swing.JLabel();
        lineGiaVe = new javax.swing.JLabel();
        pnGhiChu = new javax.swing.JPanel();
        lblGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        lineGhiChu = new javax.swing.JLabel();
        btnLuu = new custom_components.ButtonCustom();
        btnHuy = new custom_components.ButtonCustom();
        pnMaLoTrinh = new javax.swing.JPanel();
        lblMaLoTrinh = new javax.swing.JLabel();
        txtMaLoTrinh = new javax.swing.JTextField();
        lineMaLoTrinh = new javax.swing.JLabel();
        lblMaLoTrinhError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        btnBack.setBorder(null);
        btnBack.setBorderColor(new java.awt.Color(255, 255, 255));
        btnBack.setRadius(45);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        pnMain.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 80));

        lblPageTitle.setFont(new java.awt.Font("Mulish ExtraBold", 1, 27)); // NOI18N
        lblPageTitle.setText("Thêm vé");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPageTitle)
                .addContainerGap(1047, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblPageTitle)
                .addGap(21, 21, 21))
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setOpaque(false);

        pnMaVe.setBackground(new java.awt.Color(255, 255, 255));
        pnMaVe.setPreferredSize(new java.awt.Dimension(350, 83));

        lblMaVe.setBackground(new java.awt.Color(255, 204, 0));
        lblMaVe.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblMaVe.setForeground(new java.awt.Color(102, 153, 255));
        lblMaVe.setText("Mã vé *");

        txtMaVe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaVe.setForeground(new java.awt.Color(51, 51, 51));
        txtMaVe.setBorder(null);
        txtMaVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaVeMouseClicked(evt);
            }
        });

        lineMaVe.setBackground(new java.awt.Color(102, 153, 255));
        lineMaVe.setOpaque(true);
        lineMaVe.setPreferredSize(new java.awt.Dimension(400, 1));

        lblMaVeError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMaVeError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnMaVeLayout = new javax.swing.GroupLayout(pnMaVe);
        pnMaVe.setLayout(pnMaVeLayout);
        pnMaVeLayout.setHorizontalGroup(
            pnMaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaVeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMaVeLayout.createSequentialGroup()
                        .addComponent(lblMaVeError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnMaVeLayout.createSequentialGroup()
                        .addComponent(lineMaVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMaVeLayout.createSequentialGroup()
                        .addGroup(pnMaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaVe)
                            .addComponent(lblMaVe))
                        .addGap(46, 46, 46))))
        );
        pnMaVeLayout.setVerticalGroup(
            pnMaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblMaVeError)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnXoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaTrang.setForeground(new java.awt.Color(170, 170, 170));
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXoaTrangMousePressed(evt);
            }
        });

        pnTenTour.setBackground(new java.awt.Color(255, 255, 255));
        pnTenTour.setPreferredSize(new java.awt.Dimension(350, 77));

        lblTenTour.setBackground(new java.awt.Color(255, 204, 0));
        lblTenTour.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblTenTour.setForeground(new java.awt.Color(102, 153, 255));
        lblTenTour.setText("Tên Tour *");

        txtTenTour.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTenTour.setForeground(new java.awt.Color(51, 51, 51));
        txtTenTour.setBorder(null);
        txtTenTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenTourMouseClicked(evt);
            }
        });

        lblTenTourError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTenTourError.setForeground(new java.awt.Color(255, 0, 0));

        lineTenTour.setBackground(new java.awt.Color(102, 153, 255));
        lineTenTour.setOpaque(true);
        lineTenTour.setPreferredSize(new java.awt.Dimension(400, 1));

        javax.swing.GroupLayout pnTenTourLayout = new javax.swing.GroupLayout(pnTenTour);
        pnTenTour.setLayout(pnTenTourLayout);
        pnTenTourLayout.setHorizontalGroup(
            pnTenTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTenTourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTenTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenTour, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTenTourLayout.createSequentialGroup()
                        .addGroup(pnTenTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenTourError, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenTour))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnTenTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnTenTourLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lineTenTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnTenTourLayout.setVerticalGroup(
            pnTenTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTenTourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenTour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenTourError, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnTenTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnTenTourLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(lineTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        pnMaDuKhach.setBackground(new java.awt.Color(255, 255, 255));
        pnMaDuKhach.setPreferredSize(new java.awt.Dimension(350, 83));

        lblMaDuKhach.setBackground(new java.awt.Color(255, 204, 0));
        lblMaDuKhach.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblMaDuKhach.setForeground(new java.awt.Color(102, 153, 255));
        lblMaDuKhach.setText("Mã du khách *");

        txtMaDuKhach.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaDuKhach.setForeground(new java.awt.Color(51, 51, 51));
        txtMaDuKhach.setBorder(null);
        txtMaDuKhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaDuKhachMouseClicked(evt);
            }
        });

        lineMaDuKhach.setBackground(new java.awt.Color(102, 153, 255));
        lineMaDuKhach.setOpaque(true);
        lineMaDuKhach.setPreferredSize(new java.awt.Dimension(400, 1));

        lblMaDuKhachError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMaDuKhachError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnMaDuKhachLayout = new javax.swing.GroupLayout(pnMaDuKhach);
        pnMaDuKhach.setLayout(pnMaDuKhachLayout);
        pnMaDuKhachLayout.setHorizontalGroup(
            pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                        .addComponent(lblMaDuKhachError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                        .addComponent(lineMaDuKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                        .addGroup(pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDuKhach)
                            .addComponent(lblMaDuKhach))
                        .addGap(46, 46, 46))))
        );
        pnMaDuKhachLayout.setVerticalGroup(
            pnMaDuKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaDuKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaDuKhach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineMaDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblMaDuKhachError)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setOpaque(false);

        pnGiaVe.setBackground(new java.awt.Color(255, 255, 255));
        pnGiaVe.setPreferredSize(new java.awt.Dimension(350, 77));

        lblGiaVe.setBackground(new java.awt.Color(255, 204, 0));
        lblGiaVe.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblGiaVe.setForeground(new java.awt.Color(102, 153, 255));
        lblGiaVe.setText("Giá vé *");

        txtGiaVe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtGiaVe.setForeground(new java.awt.Color(51, 51, 51));
        txtGiaVe.setBorder(null);
        txtGiaVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGiaVeMouseClicked(evt);
            }
        });

        lblGiaVeError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblGiaVeError.setForeground(new java.awt.Color(255, 0, 0));

        lineGiaVe.setBackground(new java.awt.Color(102, 153, 255));
        lineGiaVe.setOpaque(true);
        lineGiaVe.setPreferredSize(new java.awt.Dimension(400, 1));

        javax.swing.GroupLayout pnGiaVeLayout = new javax.swing.GroupLayout(pnGiaVe);
        pnGiaVe.setLayout(pnGiaVeLayout);
        pnGiaVeLayout.setHorizontalGroup(
            pnGiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaVeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaVe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnGiaVeLayout.createSequentialGroup()
                        .addGroup(pnGiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGiaVeError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiaVe))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnGiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnGiaVeLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(lineGiaVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnGiaVeLayout.setVerticalGroup(
            pnGiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaVeLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblGiaVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblGiaVeError)
                .addGap(8, 8, 8))
            .addGroup(pnGiaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaVeLayout.createSequentialGroup()
                    .addGap(0, 74, Short.MAX_VALUE)
                    .addComponent(lineGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        pnGhiChu.setPreferredSize(new java.awt.Dimension(350, 61));

        lblGhiChu.setBackground(new java.awt.Color(255, 204, 0));
        lblGhiChu.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(153, 153, 153));
        lblGhiChu.setText("Ghi chú");

        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(51, 51, 51));
        txtGhiChu.setBorder(null);
        txtGhiChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGhiChuMouseClicked(evt);
            }
        });

        lineGhiChu.setBackground(new java.awt.Color(102, 153, 255));
        lineGhiChu.setOpaque(true);
        lineGhiChu.setPreferredSize(new java.awt.Dimension(780, 1));

        javax.swing.GroupLayout pnGhiChuLayout = new javax.swing.GroupLayout(pnGhiChu);
        pnGhiChu.setLayout(pnGhiChuLayout);
        pnGhiChuLayout.setHorizontalGroup(
            pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGhiChuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnGhiChuLayout.createSequentialGroup()
                        .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnGhiChuLayout.setVerticalGroup(
            pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGhiChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGhiChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnLuu.setBackground(new java.awt.Color(72, 167, 235));
        btnLuu.setBorder(null);
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("LƯU");
        btnLuu.setBorderColor(new java.awt.Color(255, 255, 255));
        btnLuu.setColor(new java.awt.Color(72, 167, 235));
        btnLuu.setColorClick(new java.awt.Color(102, 153, 255));
        btnLuu.setColorHover(new java.awt.Color(102, 153, 255));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setRadius(35);
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLuuMousePressed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 204, 204));
        btnHuy.setBorder(null);
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY");
        btnHuy.setBorderColor(new java.awt.Color(255, 255, 255));
        btnHuy.setColor(new java.awt.Color(204, 204, 204));
        btnHuy.setColorClick(new java.awt.Color(153, 153, 153));
        btnHuy.setColorHover(new java.awt.Color(153, 153, 153));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setRadius(35);
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHuyMousePressed(evt);
            }
        });

        pnMaLoTrinh.setBackground(new java.awt.Color(255, 255, 255));
        pnMaLoTrinh.setPreferredSize(new java.awt.Dimension(350, 83));

        lblMaLoTrinh.setBackground(new java.awt.Color(255, 204, 0));
        lblMaLoTrinh.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        lblMaLoTrinh.setForeground(new java.awt.Color(102, 153, 255));
        lblMaLoTrinh.setText("Mã lộ trình *");

        txtMaLoTrinh.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtMaLoTrinh.setForeground(new java.awt.Color(51, 51, 51));
        txtMaLoTrinh.setBorder(null);
        txtMaLoTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaLoTrinhMouseClicked(evt);
            }
        });

        lineMaLoTrinh.setBackground(new java.awt.Color(102, 153, 255));
        lineMaLoTrinh.setOpaque(true);
        lineMaLoTrinh.setPreferredSize(new java.awt.Dimension(400, 1));

        lblMaLoTrinhError.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMaLoTrinhError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnMaLoTrinhLayout = new javax.swing.GroupLayout(pnMaLoTrinh);
        pnMaLoTrinh.setLayout(pnMaLoTrinhLayout);
        pnMaLoTrinhLayout.setHorizontalGroup(
            pnMaLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaLoTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMaLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMaLoTrinhLayout.createSequentialGroup()
                        .addComponent(lblMaLoTrinhError, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnMaLoTrinhLayout.createSequentialGroup()
                        .addComponent(lineMaLoTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMaLoTrinhLayout.createSequentialGroup()
                        .addGroup(pnMaLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLoTrinh)
                            .addComponent(lblMaLoTrinh))
                        .addGap(46, 46, 46))))
        );
        pnMaLoTrinhLayout.setVerticalGroup(
            pnMaLoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaLoTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaLoTrinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lineMaLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblMaLoTrinhError)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnMaLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnGiaVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnMaLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(pnGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(pnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnTenTour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnMaDuKhach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnMaDuKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaTrang)
                .addGap(49, 49, 49))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        pnMain.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaVeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaVeMouseClicked

    private void txtTenTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenTourMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTourMouseClicked

    private void btnXoaTrangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaTrangMousePressed
        xoaTrang();
    }//GEN-LAST:event_btnXoaTrangMousePressed

    private void txtGiaVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGiaVeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaVeMouseClicked

    private void txtGhiChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGhiChuMouseClicked

    }//GEN-LAST:event_txtGhiChuMouseClicked

    private void btnLuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMousePressed
        luuVe();
    }//GEN-LAST:event_btnLuuMousePressed

    private void btnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMousePressed
        this.dispose();
    }//GEN-LAST:event_btnHuyMousePressed

    private void txtMaDuKhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaDuKhachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDuKhachMouseClicked

    private void txtMaLoTrinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaLoTrinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLoTrinhMouseClicked

    private void luuVe() {
        String maVe = txtMaVe.getText().trim();
        String maDK = txtMaDuKhach.getText().trim();
        String tenTour = txtTenTour.getText().trim();
        String maLT = txtMaLoTrinh.getText().trim();
        String giaVe = txtGiaVe.getText().trim();
        String ghiChu = txtGhiChu.getText().trim();
        
        if(checkInput(maVe, maDK, tenTour, maLT, giaVe, ghiChu))
        {
            Ve ve = new Ve(Integer.parseInt(maVe), maDK, tenTour, maLT, Double.parseDouble(giaVe), ghiChu);
            if(VeDAO.addVe(ve))
            {
                FrmQLVe.loadData();
                JOptionPane.showMessageDialog(null, "Thêm vé thành công");
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Lưu vé không thành công");
        }
    }
    private void textboxMousePress(MouseEvent evt) {
        Object o = evt.getSource();
        for(int i = 0; i < listTextbox.length; i++)
        {
            if(o.equals(listTextbox[i]))
            {
                Font font = listLabelForTextBox[i].getFont();
                listLabelForTextBox[i].setFont(new Font(font.getName(), Font.BOLD, font.getSize()));
                listLabelForTextBox[i].setForeground(labelFocusColor);
                listLineForTextBox[i].setBackground(labelFocusColor);
            }
            else
            {
                 Font font = listLabelForTextBox[i].getFont();
                listLabelForTextBox[i].setFont(new Font(font.getName(), Font.PLAIN, font.getSize()));
                listLabelForTextBox[i].setForeground(labelColor);
                listLineForTextBox[i].setBackground(labelColor);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_components.ButtonCustom btnBack;
    private custom_components.ButtonCustom btnHuy;
    private custom_components.ButtonCustom btnLuu;
    private javax.swing.JLabel btnXoaTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGiaVe;
    private javax.swing.JLabel lblGiaVeError;
    private javax.swing.JLabel lblMaDuKhach;
    private javax.swing.JLabel lblMaDuKhachError;
    private javax.swing.JLabel lblMaLoTrinh;
    private javax.swing.JLabel lblMaLoTrinhError;
    private javax.swing.JLabel lblMaVe;
    private javax.swing.JLabel lblMaVeError;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblTenTour;
    private javax.swing.JLabel lblTenTourError;
    private javax.swing.JLabel lineGhiChu;
    private javax.swing.JLabel lineGiaVe;
    private javax.swing.JLabel lineMaDuKhach;
    private javax.swing.JLabel lineMaLoTrinh;
    private javax.swing.JLabel lineMaVe;
    private javax.swing.JLabel lineTenTour;
    private javax.swing.JPanel pnGhiChu;
    private javax.swing.JPanel pnGiaVe;
    private javax.swing.JPanel pnMaDuKhach;
    private javax.swing.JPanel pnMaLoTrinh;
    private javax.swing.JPanel pnMaVe;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTenTour;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGiaVe;
    private javax.swing.JTextField txtMaDuKhach;
    private javax.swing.JTextField txtMaLoTrinh;
    private javax.swing.JTextField txtMaVe;
    private javax.swing.JTextField txtTenTour;
    // End of variables declaration//GEN-END:variables

}
